[project]
name = "easyofd"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fonttools==4.43.1",
    "loguru==0.7.2",
    "pyasn1>=0.6.0",
    "pymupdf==1.23.4",
    "reportlab==3.6.13",
    "xmltodict==0.13.0",
]
